version: '3'
services:
  webmin-samba:
    image: kvvtest100/webmin-samba:07.02.2023
    ports:
      - 80:80
      - 139:139
      - 445:445
    volumes:
      - ./data:/data
      - ./backup_configs:/backup_configs
    environment:
      - WEBMIN_PASSWORD=webmin1
      - WEBMIN_URL=/webmintest
      - REDIRECT_PORT=80
